class Core {
	tag="Core";
	#include "Network\module.hpp"
	#include "Music\module.hpp"
	#include "Core\module.hpp"
	#include "Whitelist\module.hpp"
	#include "Stats\module.hpp"
	#include "Settings\module.hpp"
	#include "Action\module.hpp"
	#include "Keypress\module.hpp"
	#include "Config\module.hpp"
	#include "Array\module.hpp"
	#include "BIS\module.hpp"
	#include "Storage\module.hpp"
	#include "Shops\module.hpp"
	#include "Licenses\module.hpp"
	#include "Roads\module.hpp"
	#include "Chat\module.hpp"
	#include "String\module.hpp"
	#include "Locations\module.hpp"
	#include "Setup\module.hpp"
	#include "ATM\module.hpp"
	#include "Fuel\module.hpp"
	#include "Gear\module.hpp"
	#include "Keys\module.hpp"
	#include "Garage\module.hpp"
	#include "Dance\module.hpp"
	#include "Hunger\module.hpp"
	#include "Tag\module.hpp"
	#include "Hud\module.hpp"
};